### ISSUE TITLE
Get full URL? [question]

### ISSUE THREAD

**Issue by tasmaniski** [mtymek/blast-base-url#14]
Is it possible to get full URL like **http://url-site.com/** 

I am using it in Expressive app and need full URL to share page on social media like facebook.
For eg.

```
// this should return  http://url-site.com/share-page-facebook
$this->basePath('/share-page-to-facebook'); 
```

**Comment by mtymek** [comment]
Hi,

It is not the purpose of this library :-)
Please look into ServerUrl helper from here: https://github.com/zendframework/zend-expressive-helpers - it seems to be what you need!

**Comment by tasmaniski** [comment]
Yes, exactly :) 
Thanks!

`$this->serverUrl('/path')`
