### ISSUE TITLE
Support Zend Twig Renderer

### ISSUE THREAD

**Issue by jbelien** [mtymek/blast-base-url#16]
At the moment, it supports by default "only" Zend View, would it be possible to also support [Zend Expressive Twig Renderer](https://github.com/zendframework/zend-expressive-twigrenderer/) through `ConfigProvider.php` ?

Thanks a lot :)

**Comment by mtymek** [comment]
Feel free to drop a PR ;-)

**Comment by jbelien** [comment]
Not sure how it would be best to implement this but I'll have a look at it :)
