### ISSUE TITLE
BasePath never empty 

### ISSUE THREAD

**Issue by basz** [mtymek/blast-base-url#5]
My happy path goes through [here](https://github.com/mtymek/blast-base-url/blob/master/src/BaseUrlFinder.php#L97) and as such basePath is '/' when I think it should be ''. (Well  it works when I define it as ''.) Not sure if I am doing it wrong? 

I now always get a 404 for any uri other then the homepage.

**Comment by jyggen** [comment]
I've noticed that the path is missing a leading slash once it's gone through this middleware (e.g. `/foo/bar` becomes `foo/bar`). If I change so a leading slash is added everything's working again.

**Comment by mtymek** [comment]
@basz it is OK for base **path** to be "/" - it is used build links for assets.
If you want to use it for routing, you should be using base **url**.

**Comment by mtymek** [comment]
@jyggen this issue is fixed with #8.
